name: sequana_depletion
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python>=3.10
- bwa
- sambamba
- samtools>=1.15
- pigz
- graphviz
- pulp>=2.8
- pip:
  - sequana
  - sequana_pipetools
