# Schema validator for the quality_control
# author: Thomas Cokelaer, Etienne Kornobis

type: map
mapping:
    "input_directory":
        type: str
        required: True
    "input_readtag":
        type: str
        required: False
    "input_pattern":
        type: str
        required: False
    "general":
        type: map
        mapping:
            "reference":
               type: str
               required: True
            "mode":
               type: str
               required: True
               enum: [selection, depletion]
    "bwa":
        type: map
        mapping:
            "index_algorithm":
                type: str
                required: False
            "options":
                type: str
                required: False
            "threads":
                type: int
                required: False
            "tmp_directory":
                type: str
                required: False
    "samtools":
        type: map
        mapping:
            "threads":
                type: int
                required: False
